### ISSUE TITLE
Raster reconstruction

### ISSUE THREAD

**Issue by brmather** [GPlates/gplately#15]
It would be good to have a raster reconstruction object that is highly efficient. @cpalfonso I have implemented a very basic effort by, converting rasters to points and using the in-built pygplates plate partitioner to reconstruct them,

https://github.com/GPlates/gplately/blob/56be2a2f51015901c9d59353a1d2e77624f92098/gplately/grids.py#L654-L663

But from what we have discussed this is very slow for large numbers of points. Can you make a contribution here?

**Comment by jcannon-gplates** [comment]
I can see from the highlighted code above that each point is wrapped in a pygplates feature and then partitioned using the static polygons. And then these point _features_ are reconstructed to get the reconstructed grid locations for the reconstructed raster.

If you want to speed this up you can use the `point_in_polygons` module in PlateTectonicTools (which uses a spatial tree to speed up the process of finding which polygons overlap which points that is beneficial when the points are roughly uniformly distributed). Just using that can make a fairly big difference in speed in this type of scenario. There's an [example here](https://github.com/EarthByte/PlateTectonicTools/blob/200962b630ecbac738cb586aa54e9211d7643675/ptt/utils/points_in_polygons.py#L27-L58) which finds the plate ID associated with each point. Then you could directly use this plate ID with [RotationModel.get_rotation(time, plate_id)](https://www.gplates.org/docs/pygplates/generated/pygplates.rotationmodel#pygplates.RotationModel.get_rotation) that returns a [FiniteRotation](https://www.gplates.org/docs/pygplates/generated/pygplates.finiterotation) that can directly reconstruct the point as `reconstructed_point = finite_rotation * point`. And the conversions to/from lat/lon and pygplates.PointOnSphere can be done as `point = pygplates.PointOnSphere(lat, lon)` and `recon_lat, recon_lon = reconstructed_point.to_lat_lon()` (noting that lat is before lon, the opposite of GMT, since it's been that way in GPlates since the dawn of time). A minor addition might be to group points with the same plate ID into a [MultiPoinOnSphere](https://www.gplates.org/docs/pygplates/generated/pygplates.multipointonsphere) in order to rotate them with one call `reconstructed_multi_point = finite_rotation * multi_point` and convert back to a lat/lon array in one call `recon_lat_lon_array = reconstructed_multi_point.to_lat_lon_array()` (but I'm not sure if this would speed things up much, if at all, and might just complicate things).

So it might be worth special-casing point reconstruction this different way just for reconstructing rasters to speed things up (perhaps as a private method in class Raster).

**Comment by brmather** [comment]
Thanks @jcannon-gplates, I think the `point_in_polygons` routine in PTT use a k-d tree for speedy lookups if memory serves me correctly. @cpalfonso mentioned he has developed a routine that grids the static polygons and reconstructs them back in time which is another way of looking at this. In any case we should take advantage of the grid structure to partition points correctly and quickly.
