### ISSUE TITLE
error when using pygplates imported via gplately, but not via normal pygplates

### ISSUE THREAD

**Issue by nickywright** [GPlates/gplately#150]
I get an error when I try and use the gplately version of `pygplates`, but not the normally imported version of pygplates, when I try and use `pygplates.Feature()`. See screenshot with error.

<img width="1311" alt="Screenshot 2023-12-04 at 2 33 54 pm" src="https://github.com/GPlates/gplately/assets/19943774/677b4de0-bcbe-4935-8e7c-fa2cbdde6f70">

**Comment by michaelchin** [comment]
Hi @brmather,

I am not sure about the comments below. Why is the Feature object associated with multiple files? Can you explain a bit this Feature class. I could not really understand the purpose of this class.
https://github.com/GPlates/gplately/blob/14b41800431a90963e2ddef03400657d05fe540e/gplately/pygplates.py#L218-L220

And it seems that some of the comments were copied from pygplates doc. Maybe we should not duplicate the texts so that we don't have to change the comments each time pygplates changes its doc. Maybe a link to pygplates doc would be sufficient.

**Comment by jcannon-gplates** [comment]
On a side note: the next release of pyGPlates will have [pickle](https://docs.python.org/3/library/pickle.html) support. I think the lack of support was one of the reasons for having a GPlately version of pygplates.Feature (and FeatureCollection,  RotationModel). For example, to support parallel processing where a Feature can be reconstructed on another process using its (pickled) filename(s). So after the next pygplates release you might not need these classes - although I guess would still need them if the detected pygplates version is too old.
