### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#174]
@brmather @lauren-ilano @jcannon-gplates 
See the code below. The 'continue' statement will skip the current loop iteration. The current point will not be reconstructed. But according to the comments, it should be reconstructed.
https://github.com/GPlates/gplately/blob/f49b31695882df362fda45f7ad7fcc5bf5c7d68e/gplately/reconstruction.py#L2563-L2570

**Comment by jcannon-gplates** [comment]
Yeah I think that's a bug. Good spot!  I think that's been in there since the beginning. Removing `continue` should fix it, I think.

On a related note, as mentioned in #101, at some stage all that code can get replaced (since it's now in pyGPlates). For example, I recently did a similar thing for the [Predicting Sediment Thickness](https://github.com/EarthByte/predicting-sediment-thickness) workflow by changing [this](https://github.com/EarthByte/predicting-sediment-thickness/pull/2/commits/30a71235f794911e1c8c3f6e7305c8a8440fef5a#diff-4e3282283fd7affe324e3c94761e770bee5d2a91c1897d96c215a98cd5f6613fL496-L605) to [this](https://github.com/EarthByte/predicting-sediment-thickness/pull/2/commits/30a71235f794911e1c8c3f6e7305c8a8440fef5a#diff-4e3282283fd7affe324e3c94761e770bee5d2a91c1897d96c215a98cd5f6613fR934-R997).

**Comment by michaelchin** [comment]
> Yeah I think that's a bug. Good spot! I think that's been in there since the beginning. Removing `continue` should fix it, I think.
> 
> On a related note, as mentioned in #101, at some stage all that code can get replaced (since it's now in pyGPlates). For example, I recently did a similar thing for the [Predicting Sediment Thickness](https://github.com/EarthByte/predicting-sediment-thickness) workflow by changing [this](https://github.com/EarthByte/predicting-sediment-thickness/pull/2/commits/30a71235f794911e1c8c3f6e7305c8a8440fef5a#diff-4e3282283fd7affe324e3c94761e770bee5d2a91c1897d96c215a98cd5f6613fL496-L605) to [this](https://github.com/EarthByte/predicting-sediment-thickness/pull/2/commits/30a71235f794911e1c8c3f6e7305c8a8440fef5a#diff-4e3282283fd7affe324e3c94761e770bee5d2a91c1897d96c215a98cd5f6613fR934-R997).

Thanks John.

I will remove the "continue" and do some tests.

**Comment by michaelchin** [comment]
fixed in e7112cac760e3317e312d6c89a30392f61c8fee7
