### ISSUE TITLE
pygplate.py

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#176]
@brmather @lauren-ilano @laurilano 

At the beginning of this file, we can see the comments below.

"""
A light wrapping of some [`pyGPlates`](https://www.gplates.org/docs/pygplates/index.html) 
classes to keep track of filenames.

Each object listed here will have a `self.filenames` attribute.
"""

I can understand tracking filenames for RotationModel and FeatureCollection. But why can Feature be associated with "filenames"?

Another question, is the code in this file completed? It seems to me that the pygplate.py is unfinished and not ready to be used yet.

**Comment by brmather** [comment]
> I can understand tracking filenames for RotationModel and FeatureCollection. But why can Feature be associated with "filenames"?

Can you create a `pygplates.feature` from a filename? If not, we can probably delete this function.

> Another question, is the code in this file completed? It seems to me that the pygplate.py is unfinished and not ready to be used yet.

I haven't wrapped all the `pygplates` functions to include a filename, just the main ones. Since `pygplates` is imported in the namespace all the existing `pygplates` functions in there will be accessible. i.e.

```python
from gplately import pygplates
```

will have a complete set of `pygplates` functions, with RotationModel and FeatureCollection being overwritten to include filenames for parallelism.

The next release of pygplates will support pickling (and therefore parallel support), so once that's released we can remove our light modification of pygplates objects and enforce the pygplates version in `project.toml`.

**Comment by jcannon-gplates** [comment]
> The next release of pygplates will support pickling (and therefore parallel support), so once that's released we can remove our light modification of pygplates objects and enforce the pygplates version in project.toml.

Good idea. It won't be long until the next pygplates release.
