### ISSUE TITLE
subduction zone with dual polarities 

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#188]
This bug was reported by Sabin and is a part of #183.

I tried to reproduce the bug. The steps I had taken

- installed GPlately "update-data-download" branch
- run https://github.sydney.edu.au/EarthByte/EarthByteWorkflows/blob/pacific-maps/Maps/GPlately_orthographic_maps.ipynb

I don't see the subduction zone with dual polarities. 

<img width="875" alt="Screenshot 2024-06-06 at 10 44 58 AM" src="https://github.com/GPlates/gplately/assets/2688316/9ff80463-7b86-4261-ab4f-0cb5b94c8439">

**Comment by michaelchin** [comment]
The screenshot below was provide by Sabin. I put the screenshot here for comparison purpose.

![336353494-1df5d201-642b-4917-a8de-86e4369fbf20](https://github.com/GPlates/gplately/assets/2688316/ccbfefa4-a5c2-4961-9b64-8318bfbb9a7d)

**Comment by michaelchin** [comment]
I had made another attempt to reproduce the "dual polarities" bug with the latest Muller2019 model and latest gplately code. The bug did not show. See the screenshot below.

<img width="448" alt="Screenshot 2024-07-03 at 6 02 09 PM" src="https://github.com/GPlates/gplately/assets/2688316/162671ae-397a-4072-bd16-fd0e62e4b0d2">

I guess this "dual polarities" bug must only happen with a particular version Muller2019 model and certain revision of gplately code. To reproduce this bug, I need to know

- which revision of gplately code was used
- a copy of the  Muller2019 model  files which was used

I will contact customer for the info listed above. Add "Pending" label for now.

**Comment by michaelchin** [comment]
I have sent the customer an email "Progress report - Issue #188: subduction zone with dual polarities". Waiting for the customer's response.

**Comment by michaelchin** [comment]
The client said "_If the issue is not recurring, then we could park it until it resurfaces with the double polarity._". It seems the client is not unhappy with the idea of putting this issue on ice.

**Comment by michaelchin** [comment]
Some new development. I was debugging https://github.com/GPlates/gplately/issues/269 and modified some topological lines in muller2019. I saw something. See the screenshot below. I am not sure if it is a data problem or code defect.

@jcannon-gplates Is this something we need to fix? I have uploaded the topology file here  https://repo.gplates.org/webdav/gplately-test-data/issue-188/muller2019/Topologies/

<img width="1066" alt="Screenshot 2024-10-22 at 10 39 37 AM" src="https://github.com/user-attachments/assets/f94838d6-7071-4789-afa1-b137986dc2c8">
<img width="1067" alt="Screenshot 2024-10-22 at 10 40 22 AM" src="https://github.com/user-attachments/assets/b17ac048-f8bb-4e42-ab19-b65f7f16466e">

**Comment by jcannon-gplates** [comment]
That's interesting - there's definitely something not right happening. I loaded your data, and then tried to replicate your situation (from the original data) by extending the two lines so that they intersect. However what I got worked fine...

![image](https://github.com/user-attachments/assets/fcb63e08-149a-4f02-b35c-2b14b97e128b)

It looks like you replaced some of the line sections contributing to the topological line with simpler straight line sections. Is that right? In any case, I'll have a deeper look, thanks.

**Comment by jcannon-gplates** [comment]
> Some new development. I was debugging https://github.com/GPlates/gplately/issues/269 and modified some topological lines in muller2019. I saw something. See the screenshot below. I am not sure if it is a data problem or code defect.

I think I know what's happening. You mentioned in the meeting today that you reversed some of the line sections (that contribute to the subduction zone topological line). When I tried that I could also reproduce your screenshot.

The issue is the reversal flag of each line section (ie, whether they're reversed when contributing to the topological line) is built into the topological line *when it is created* - there's an algorithm that automatically determines the best combination of reversal flags. So when you reverse a line section *after the topological line has been built* it still uses the old reversal flags, and hence the problem. A long time ago I had debated whether to run the automatic reversal algorithm each time a topology is loaded - but it's not cheap and easier to run at build time.

If I move the two intersecting line sections (yellow arrows) a little you can then see the problem with the topological line (blue arrow) more clearly...

![image](https://github.com/user-attachments/assets/056bd7f6-d350-4247-8203-3d5682de7d54)

The solution in this case it to edit the topological line (`E`) and then simply hit the `Apply` button to re-generate new reversal flags (and store them in the topological line).

**Comment by jcannon-gplates** [comment]
Going back to the original screenshot from Sabin at 59Ma, I loaded the Muller 2019 model and there's a duplicate subduction zone in the problem area. You can see in the screenshot below, there's two sets of subduction teeth along there. But they both have the correct (matching) subduction polarity, so both sets of teeth are on the same side.

So, I suspect the "dual" polarities were due to "dual" subduction zone lines with **opposite** polarities (in the model Sabin used to make his screenshot). So unless we can get that particular model, I'd say this is probably *not* a bug in GPlately (and this issue could be closed).

![image](https://github.com/user-attachments/assets/3bd60f00-f6bc-466f-a0cb-d9923649c1be)

**Comment by michaelchin** [comment]
Thanks a lot, John. Great work!!!
Close this issue now.
