### ISSUE TITLE
age-gridding seems to be breaking down entirely 

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#190]
The info below was provided by Sabin.

Maybe it’s something I’m doing wrong here, but the gplately method for age-gridding seems to be breaking down entirely if the topology section is a topological line. The South Atlantic is essentially broken in this model from the beginning.

 

https://filesender.aarnet.edu.au/?s=download&token=90fe2b27-ae83-474c-b621-8e782639ede3

 

Each point is tagged as a MidOceanicRidge, and the topological line itself is tagged correctly too. So I’m not sure what’s going on. I then added gpml:leftPlate and gpml:rightPlate to the topological line, in the hope it will fix the problem. But no luck.

 

Ben, maybe you have an insight into a basic aspect, which is, does the workflow deal with topological lines (MORs) at all? If not, it would need to be added as a very high priority – but perhaps there’s something I’m missing???

<img width="1560" alt="Screenshot 2024-06-07 at 12 20 22 PM" src="https://github.com/GPlates/gplately/assets/2688316/68826c31-6702-45a6-8b84-eeb23ba2df44">
<img width="1552" alt="Screenshot 2024-06-07 at 12 20 33 PM" src="https://github.com/GPlates/gplately/assets/2688316/08dff41c-3ed6-43db-a634-97682aacb5c4">
<img width="1541" alt="Screenshot 2024-06-07 at 12 20 46 PM" src="https://github.com/GPlates/gplately/assets/2688316/89c322e6-8c4f-433b-8daa-600c14b09ce7">
<img width="1556" alt="Screenshot 2024-06-07 at 12 21 38 PM" src="https://github.com/GPlates/gplately/assets/2688316/c955497f-bd89-4f72-9daf-c3a90c46f41f">

**Comment by jcannon-gplates** [comment]
I think I've found the issue - I'll write more up later tonight (or tomorrow).

**Comment by jcannon-gplates** [comment]
I think the MOR is not being detected as a spreading feature (at [this](https://github.com/GPlates/gplately/blob/c5b0d1c075961643cb518ec227a896e6556b84de/gplately/ptt/separate_ridge_transform_segments.py#L362) point in the code, called from [here](https://github.com/GPlates/gplately/blob/c5b0d1c075961643cb518ec227a896e6556b84de/gplately/oceans.py#L1743-L1748)).

I had a look at the MOR feature in the above example (specifically `South Atlantic MOR topology 114-85 Ma`) and I think it's an issue with that feature not having a [gpml:reconstructionMethod](https://www.gplates.org/docs/pygplates/generated/pygplates.feature#pygplates.Feature.get_reconstruction_method) property to indicate that it's an MOR (only having a left and right plate ID is not quite sufficient). So instead the code is looking for a plate/conjugate ID pair and not finding them, and hence ignoring the MOR (when generating seed points along the ridge).

I can see why this is happening to MORs that are *topological lines*. An MOR that is a topological line doesn't need these properties to determine its motion (like a non-topological line does) since its motion is determined exclusively by the *independently* moving points it's topologically connected to. However for age grids, these properties are needed to move the age-gridding seed points (which start out along the MOR).

So, adding the following properties to that feature (eg, using GPlates) should hopefully fix that:

1. `gpml:reconstructionMethod` property with a value of `HalfStageRotationVersion3`.
    - Actually, for age gridding the *version* of half-stage doesn't matter (it's not used), but might as well be the latest (version 3).
2. `gpml:geometryImportTime` property with the time at which spreading *starts* (eg, time of appearance of MOR).
    - Actually, this property isn't needed at all for the age gridding since age gridding only needs the stage pole of the MOR (from left/right plate IDs) and doesn't need to position the MOR (relative to the left plate) since it's a topological line (ie, already positioned).
    - So maybe don't add this property. And just leave it if there's one already.

**Comment by michaelchin** [comment]
Waiting for customer's feedback on John's solution. Add label 'pending'. Pending on customer's feedback.

**Comment by sabinz** [comment]
John, this works great, thanks - exactly the missing piece that was needed. This issue can now be closed.
