### ISSUE TITLE
split between ridge and transform segments doesn’t always work

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#193]
This problem was reported by Nicky at https://github.com/GPlates/gplately/issues/183#issuecomment-2149454229

It seems that the problem is the "ridges" have not been identified properly. See the screenshots below.

Hi @jcannon-gplates,
You are more familiar with the topology stuff. Any idea why the line is half-red and half-grey at 52Ma. How do we decide if a boundary section a ridge or other things?

<img width="948" alt="Screenshot 2024-06-13 at 12 33 41 PM" src="https://github.com/GPlates/gplately/assets/2688316/4ceb524e-3754-4cb2-8b2b-916b8b2b758c">

![336799577-401597ba-2ba0-4c07-ad17-fc05d5c6f2f9](https://github.com/GPlates/gplately/assets/2688316/d1b7561a-11a7-4cd1-96ac-876c2c70d56e)

![336799522-d4cd5a76-f5c7-4906-b1f0-e43c8aecc758](https://github.com/GPlates/gplately/assets/2688316/01173124-23ec-4ccc-baf7-9d0544ae7a93)

**Comment by michaelchin** [comment]
The following comments by Nicky at https://github.com/GPlates/gplately/issues/183#issuecomment-2149454229 may also be related to this problem. But I am not entirely sure since I am lack of background info or necessary knowledge to understand. 

@nickywright could you please confirm if the following comments are also about "the ridges have not been identified properly"? Thanks.

<img width="879" alt="Screenshot 2024-06-13 at 12 47 13 PM" src="https://github.com/GPlates/gplately/assets/2688316/de256275-508f-4579-b05e-8fd8486fc9c6">

**Comment by jcannon-gplates** [comment]
> In 2016 I tested a lot of values for the ‘deviation angle’ that I think this code is based on (if it’s the same as Simon’s code?

Yes it's based an a deviation angle - the code wasn't based directly on Simon's code but it probably follows the same principle.

It looks like GPlately is [currently using](https://github.com/GPlates/gplately/blob/c5b0d1c075961643cb518ec227a896e6556b84de/gplately/plot.py#L444) the default angle of [45 degrees](https://github.com/GPlates/gplately/blob/c5b0d1c075961643cb518ec227a896e6556b84de/gplately/ptt/separate_ridge_transform_segments.py#L41). But, as you noted, I'd imagine it'd be hard to find a deviation angle that works well for all MOR features in a model.

> but the code to split between ridge and transform segments for some reason thinks half of this boundary is a ridge (it shouldn’t be though) – and this segment is fine at 59 Ma so it might be ‘flipping’ between a transform and a ridge segment in an animation?

I think it's because the stage pole (calculated from left/right plate IDs) is hovering around the deviation angle. You can see the delta velocity (visually subtract arrow on one side from arrow on the other) is starting to align with the line direction (so it's behaving more like a transform than a MOR). For comparison, the MOR line next to it (south of the Kula plate) has nicely separated ridge/transform segments because its delta velocity is actually nicely perpendicular/parallel to its ridge/transform segments. I don't think there's a deviation angle that could satisfy both these MOR lines since they are actually perpendicular to each other (but still share the same left/right plate IDs and hence have the same stage pole that deviations are based on).

A possible solution is to just give that feature a type other than `gpml:MidOceanRidge` (such as `gpml:Transform`) since only features of type MOR will get split into ridge/transform segments. I think you alluded to this when you mentioned the "Pacific-Kula **transform**" (as opposed to "Pacific-Kula MOR"). Then the entire line would be grey (which I assume is desired for a transform feature).

By the way, the ridge/transform separation code can breakdown when the stage pole location is near a segment (arc) of the line - because the deviation can easily flip for example. But I don't imagine that happens very often (and is probably quite localised *within* a particular line (eg, localised to a specific segment of the line).

**Comment by jcannon-gplates** [comment]
Sabin responded...

> Yes, I had a close look too – both of those issues can be fixed in the plate model actually. I hadn’t realised we made that transform as a MOR feature all those years back, but that is an easy fix. Philippine MOR can also be fixed, so this issue can probably be closed.

...to my email saying...

> In summary I think the MOR in the screenshot can be labelled a transform (instead of MOR).
>
> Then it’d always be grey. It actually behaves more like a transform anyway (since convergence velocity is aligned with the line) whereas the MOR next to it (south of Kula plate) has same convergence (well, same stage pole from same left/right plates) but is oriented much more appropriately for MOR spreading.

So feel free to close this issue (or leave as `wontfix`).

**Comment by michaelchin** [comment]
I will close this issue in 7 days. Leave time for customers to response

**Comment by michaelchin** [comment]
See comments above.
