### ISSUE TITLE
Use multipoint coverage to save age gridding debug data

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#208]
Instead of saving as individual points you can save as a multipoint coverage.  Basically, each point gets one or more scalar values – such as age, spreading rate, direction, obliquity, etc. 

The details is John's email. Find the email in Michael Chin's email inbox.

**Comment by jcannon-gplates** [comment]
Thanks, here's the email...

Instead of saving as individual points you can save as a multipoint coverage.  Basically, each point gets one or more scalar values – such as age, spreading rate, direction, obliquity, etc.  But it’s all compactly stored in the GPML file – so it’s much smaller and loads faster.  In isopolate, you can see how it’s done [here](https://github.com/EarthByte/presentday-agegridding/blob/79909e812d4456ed93908eb61171e772aa81eeaa/isopolate.py#L1461-L1473) (where [this function](https://github.com/EarthByte/presentday-agegridding/blob/79909e812d4456ed93908eb61171e772aa81eeaa/isopolate.py#L380) shows how the age, spreading rate, direction, obliquity, etc, are added).  This ultimately hinges around [pygplates.Feature.set_geometry()](https://www.gplates.org/docs/pygplates/generated/pygplates.feature#pygplates.Feature.set_geometry) (see the bottom example in that function).

The following screenshot shows some old isopolate output (it’s actually lines instead of multipoints, but it’s the same idea, each point gets a different colour).  And it’s easy to switch between the different output types (eg, age, spreading obliquity, etc) and colour each output type with a different palette.  This is in grey layers (that aren’t commonly seen in GPlates).

Also, if you could set the feature time-period on each GPML to [time+0.5, time-0.5] that would be great!  Because it means we can load all the GPMLs at once and animate the time slider - and only one GPML will be visible at a time.  That allows us to more easily animate the seed points to see where they go over time.  Currently, when you animate the slider you also have to disable some layers at later times so they don’t overlap the current time.

![image](https://github.com/GPlates/gplately/assets/16912600/445a2384-c671-47e1-971a-f8a594cfe39e)
