### ISSUE TITLE
a question about ridges and transforms separation

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#219]
@jcannon-gplates 

See the code snippets below. The ridges and transforms were returned separately in ptt.resolve_topologies.resolve_topologies_into_features(). Why does the ptt.separate_ridge_transform_segments.separate_features_into_ridges_and_transforms() still needed?

https://github.com/GPlates/gplately/blob/f8a8829f06fbc8631c6eba6eabecd0956d424fb8/gplately/plot.py#L445-L467

**Comment by jcannon-gplates** [comment]
I think you're right. It shouldn't be needed as far as I can tell.

In fact I think it would even give the wrong result.

Because `ptt.separate_ridge_transform_segments.separate_features_into_ridges_and_transforms()` actually reconstructs its input features (`self.ridge_transforms`), but they are already reconstructed (resolved by `ptt.resolve_topologies.resolve_topologies_into_features()`). Which means that `self.ridges, self.transforms` would be incorrect.

I think the solution is just to remove the entire call to `ptt.separate_ridge_transform_segments.separate_features_into_ridges_and_transforms()`. And just let `ptt.resolve_topologies.resolve_topologies_into_features()` do the work...

...noting that internally it calls `ptt.separate_ridge_transform_segments.separate_geometry_into_ridges_and_transforms()` which has **geometry** in the function name (not **feature**) - and hence uses the already-reconstructed geometry (at spreading time) and not a feature (which by usual definition contains **present-day** geometry that needs reconstructing). It's a bit tricky in this area because `ptt.resolve_topologies.resolve_topologies_into_features()` is actually returning **resolved** features which do **not** contain present-day geometry (which goes against the usual rule that features should contain present-day geometry).

**Comment by michaelchin** [comment]
The ridges and transforms are different after removing ptt.separate_ridge_transform_segments.separate_features_into_ridges_and_transforms(). See the screenshots below. I am not sure which one makes more sense.

<img width="906" alt="Screenshot 2024-07-09 at 2 33 26 PM" src="https://github.com/GPlates/gplately/assets/2688316/a037381f-f3a0-4dda-b2ce-c46c3d056c60">
<img width="895" alt="Screenshot 2024-07-09 at 2 38 02 PM" src="https://github.com/GPlates/gplately/assets/2688316/5d0b499e-03b2-424b-b905-2e82f1979873">

**Comment by michaelchin** [comment]
> In fact I think it would even give the wrong result.

You are right. See this screenshot. The ridges and transforms moved away from topological boundaries.

<img width="598" alt="Screenshot 2024-07-09 at 2 43 05 PM" src="https://github.com/GPlates/gplately/assets/2688316/b1fd3526-0cf7-4e4d-913f-2c9fbad5a0a8">

**Comment by jcannon-gplates** [comment]
That's great, I'm glad you noticed this in the first place!  This will affect #203 for sure.

**Comment by michaelchin** [comment]
And also, it seems self.ridge_transforms contains more geometries than (self.ridges + self.transforms). See the screenshot below. Some lines in self.ridge_transforms are neither ridges nor transforms.

<img width="930" alt="Screenshot 2024-07-09 at 3 36 20 PM" src="https://github.com/GPlates/gplately/assets/2688316/d701a05e-389b-4aa5-92f3-acf9509228f8">

**Comment by jcannon-gplates** [comment]
Yes that happens to MORs that [fail to generate a stage rotation](https://github.com/GPlates/gplately/blob/f8a8829f06fbc8631c6eba6eabecd0956d424fb8/gplately/ptt/resolve_topologies.py#L235) for various reasons stated [here](https://github.com/GPlates/gplately/blob/f8a8829f06fbc8631c6eba6eabecd0956d424fb8/gplately/ptt/separate_ridge_transform_segments.py#L341-L344) (like not having left/right plate IDs).

So they're still mid-ocean ridges but we cannot determine which parts are transforms and which parts are spreading ridges. So I think it's OK.

**Comment by michaelchin** [comment]
This issue will be fixed in https://github.com/GPlates/gplately/issues/203. See #203 for update. Close this one.
