### ISSUE TITLE
discretize polyline

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#255]
This is the first step of https://github.com/GPlates/gplately/issues/251

Return a set of points for a given polyline. The points are taken from the polyline for every a certain distance.

For example, from the starting point, along the line, take a point for every 5km(or degrees, or whatever). This does not means the direct distance between adjacent points is always 5km because the polyline may change direction between the two points. For example, if there is/are a/a few vertex/vertices between the adjacent sampling points, the direct distance between the adjacent sampling points may be shorter than 5km. But if you travel along the polyline, the distances between the adjacent sampling points are always 5km.

The pygplates has a polyline.to_tessellated() function, but the distances between points are not uniform.

**Comment by michaelchin** [comment]
another option is the distances between two adjacent sampling points are alway exactly uniform. It means the direct  distances between two adjacent sampling points are alway the same.

**Comment by jcannon-gplates** [comment]
> For example, if there is/are a/a few vertex/vertices between the adjacent sampling points, the direct distance between the adjacent sampling points may be shorter than 5km. But if you travel along the polyline, the distances between the adjacent sampling points are always 5km.

Yes I think the latter is probably what's desired - the distance as you travel *along* the polyline - at least that's how I interpreted it. To help with that you can travel along the polyline and accumulate [arc lengths](https://www.gplates.org/docs/pygplates/generated/pygplates.greatcirclearc#pygplates.GreatCircleArc.get_arc_length) of the [segments](https://www.gplates.org/docs/pygplates/generated/pygplates.polylineonsphere#pygplates.PolylineOnSphere.get_segments). When the accumulated distance exceeds the uniform distance you can [insert a point](https://www.gplates.org/docs/pygplates/generated/pygplates.greatcirclearc#pygplates.GreatCircleArc.get_arc_point) using a *normalised_distance_from_start_point* that is the leftover remainder distance (ie, `uniform_distance - accumulated_distance`) - it'll do an internal rotation from the arc's start to end point to get the intermediate point.

By the way, this is fine when converting a polyline into uniformly spaced points (which is what you're doing), but it cannot be used to tessellate a polyline into a more-densely sampled *polyline*. This is because it can change the shape of the polyline (picture the corner points, between ridge and transform segments, of a mid-ocean ridge getting removed, ie, if you join the new points together and discard the original points).

A further complication is if you also need a *normal* (to the polyline) at each point - I suspect if it isn't asked for yet, it soon will be. So, if a new uniformly-spaced point lands exactly on an original polyline vertex then the normal becomes ambiguous (is it the normal of the left or right adjacent segment?) - you could choose either (or average them) but it's not obvious which is the best approach - it could be a user option. Also the first (and potentially the last) polyline point has a similar issue, although it lands on only one segment, so I suppose it's not so much a problem. You could always make the first uniformly-spaced point be half the uniform distance by default (that could also be a user option). In any case, sounds like that's not asked for yet, so can deal with it later.

> The pygplates has a polyline.to_tessellated() function, but the distances between points are not uniform.

True, in fact I plan to add something similar to the above-mentioned at some stage. The reason I didn't so far is because of the issue in the above paragraph (about changing the shape) and the tessellation was used by the subduction convergence code, which also needed a segment *normal* (and hence I also avoided the ambiguous normal issue mentioned above).
