### ISSUE TITLE
Plotting artefacts when crossing the dateline

### ISSUE THREAD

**Issue by brmather** [GPlates/gplately#99]
Currently `gplately` wraps all geometries to the dateline, which divides topologies that cross the dateline into smaller topologies that butt up against the -180/180 degree dateline.

https://github.com/GPlates/gplately/blob/9b832088a86d36b8154172d95f037bcf237f1331/gplately/geometry.py#L168-L308

However, this does not (currently) work for geometries which use the 0/360 degree longitude convention. We need to create an additional wrapping for `central_meridian=180`, which is implemented in this function:

https://github.com/GPlates/gplately/blob/9b832088a86d36b8154172d95f037bcf237f1331/gplately/geometry.py#L398-L469

I suppose two wrappings (-180/180 and 0/360) should be done by default. I don't think this would add too much additional overhead.

**Comment by jcannon-gplates** [comment]
Are there cases where a pygplates 3D geometry is converted to a Shapely 2D geometry (using one central meridian, maybe just zero) and then later sometime those Shapely geometries are plotted using a different central meridian?

Just wondering because, for polygons, that could result in vertical lines inside the plot (instead of just at the map's side boundaries).

However in `plot.py` it looks like `shapelify_features` is delayed until plotting (ie, when you know the plot's central meridian). So I guess it's not an issue provided the plot's central meridian is passed through to it.

**Comment by michaelchin** [comment]
> However in `plot.py` it looks like `shapelify_features` is delayed until plotting (ie, when you know the plot's central meridian). So I guess it's not an issue provided the plot's central meridian is passed through to it.

I guess the problem is the central meridian was not passed through.

https://github.com/GPlates/gplately/blob/9b832088a86d36b8154172d95f037bcf237f1331/gplately/plot.py#L1926

**Comment by jcannon-gplates** [comment]
And looks like some work is being done to address that on the `plot-kw` branch (see f39008b).

**Comment by michaelchin** [comment]
anyone knows what's the status of the plot-kw branch? Is it ready to be merged or still under development?

**Comment by brmather** [comment]
@cpalfonso - is #104 safe to merge?

**Comment by cpalfonso** [comment]
Sorry everyone, I've only recently got around to tidying this work up into a couple of commits. As far as I can tell, the changes seem to work well for different central longitudes:

![image](https://github.com/GPlates/gplately/assets/60722740/2a99dcdd-9a37-444e-b53b-12b9e8813511)

I can't spot any issues with orthographic projections, either:

![image](https://github.com/GPlates/gplately/assets/60722740/79bcdf3a-3337-4a5c-bcd2-ea8857897555)

**Comment by brmather** [comment]
Thanks @cpalfonso! I'll mark this as complete.
